/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asian_paints;

import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.*;

/**
 *
 * @author Lavanjan
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /*private JPanel jPanel1;
    private JLabel jLabel2;
    private JLabel jLabel1;
    private JLabel jLabel_uname;
    private JLabel jLabel_pass;
    private JTextField jTextField_uname;
    private JPasswordField jPasswordField_pass;
    private JButton jButton_signin;
    private JButton jButton_cancel;
    private JComboBox<Object> jComboBox_position;
    private JLabel jLabel5;
    private JLabel jLabel4;
    private JLabel jLabel_pass1;
    */
    
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_uname = new javax.swing.JLabel();
        jLabel_pass = new javax.swing.JLabel();
        jTextField_uname = new javax.swing.JTextField();
        jPasswordField_pass = new javax.swing.JPasswordField();
        jButton_signin = new javax.swing.JButton();
        jButton_cancel = new javax.swing.JButton();
        jComboBox_position = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_pass1 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asian_paints/Image/log.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asian_paints/Image/App-login-manager-icon.png"))); // NOI18N

        jLabel_uname.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel_uname.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_uname.setText("Username:");

        jLabel_pass.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel_pass.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_pass.setText("Password:");

        jTextField_uname.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_uname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField_uname.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_uname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField_uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_unameActionPerformed(evt);
            }
        });

        jPasswordField_pass.setBackground(new java.awt.Color(51, 51, 51));
        jPasswordField_pass.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPasswordField_pass.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField_pass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton_signin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton_signin.setForeground(new java.awt.Color(0, 0, 0));
        jButton_signin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asian_paints/Image/Register-icon.png"))); // NOI18N
        jButton_signin.setText("SignIn");
        jButton_signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_signinActionPerformed(evt);
            }
        });

        jButton_cancel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton_cancel.setForeground(new java.awt.Color(0, 0, 0));
        jButton_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asian_paints/Image/Actions-button-cancel-icon (1).png"))); // NOI18N
        jButton_cancel.setText("Cancel");
        jButton_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelActionPerformed(evt);
            }
        });

        jComboBox_position.setBackground(new java.awt.Color(51, 51, 51));
        jComboBox_position.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jComboBox_position.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox_position.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "MANAGER", "CASHIER", "STOCK KEEPER", " " }));
        jComboBox_position.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Enter Your Personal Info & Select Your Roll");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Welcome Back ! ");

        jLabel_pass1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel_pass1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_pass1.setText("Roll:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(224, 224, 224)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel_uname)
                                    .addComponent(jLabel_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_pass1)
                                .addGap(26, 26, 26)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_cancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                .addComponent(jButton_signin))
                            .addComponent(jTextField_uname)
                            .addComponent(jPasswordField_pass)
                            .addComponent(jComboBox_position, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel5)))
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(64, 64, 64))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_uname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_uname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jPasswordField_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox_position)
                        .addGap(1, 1, 1))
                    .addComponent(jLabel_pass1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_signin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelActionPerformed
        // TODO add your handling code here:
        //CANCEL
        int esc = JOptionPane.showConfirmDialog(this, "Do you want to cancel this Operation ?");
        if (esc == JOptionPane.YES_OPTION) {
            System.exit(0);

        } else if (esc == JOptionPane.NO_OPTION) {

            JOptionPane.showMessageDialog(null, "Please Enter Your Personal Info");
        } else {
            //do nothing
        }
    }//GEN-LAST:event_jButton_cancelActionPerformed

    private void jButton_signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_signinActionPerformed
        // TODO add your handling code here:
        // LOGIN
       
        
        
        
        
        
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/Asian_Paints", "root", "");
            String uname, password, roll, sql;
            if (jTextField_uname.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Please Insert Username");
            }
            else 
            {
                 uname = jTextField_uname.getText();
                sql = "select * from `login` where username='" + uname + "';";
                pst = con.prepareStatement(sql);
                rs = pst.executeQuery();
                if (!rs.next()) {
                    //Manager mn = new Manager();
                   // mn.setVisible(true);
                   // mn.pack();
                   // mn.setLocationRelativeTo(null);
                    JOptionPane.showMessageDialog(this, "Username Invalid");
                   // Manager.jLabel_mname.setText("Welcome<"+jTextField_uname.getText()+">");
                   // this.dispose();
                }
                else
                {
                    password = jPasswordField_pass.getText();
                    if (jPasswordField_pass.getText().equals("")) {
                        JOptionPane.showMessageDialog(this, "Please Insert Password");

                    } 
                    else
                    {
                        sql = "select * from `login` where password='" + password + "';";
                        pst = con.prepareStatement(sql);
                        rs = pst.executeQuery();
                        if (!rs.next()) {
                            JOptionPane.showMessageDialog(this, "Password Invalid");
                        }
                        else 
                        {
                            roll =  jComboBox_position.getSelectedItem().toString();
                            if (String.valueOf( jComboBox_position.getSelectedItem()).equals("SELECT")) {
                                JOptionPane.showMessageDialog(null, "Please Select Your Roll");
                            }
                            else
                            {
                                sql = "select * from `login` where username='"+uname+"'&& password='"+password+"'&& roll ='"+ roll +"';";
                                pst = con.prepareStatement(sql);
                                rs = pst.executeQuery();
                                if (!rs.next()) {
                                    JOptionPane.showMessageDialog(this, "Sorry Selected roll dose't match with Username");
                                } 
                                else
                                {
                                    JOptionPane.showMessageDialog(null, "Your Login Was Successful");
                                    if ( jComboBox_position.getSelectedIndex() == 1) {
                                        
                                        Manager manager = new Manager();
                                        Manager.jLabel_mname.setText(this.jTextField_uname.getText());
                                        manager.setVisible(true);
                                        this.setVisible(false);

                                    } 
                                    else if ( jComboBox_position.getSelectedIndex() == 2) {
                                        Cashier cashier = new Cashier();
                                        Cashier.jLabel_cname.setText(this.jTextField_uname.getText());
                                        cashier.setVisible(true);
                                        this.setVisible(false);

                                    } 
                                    else
                                    {
                                        Stock_Keeper keeper = new Stock_Keeper();
                                        Stock_Keeper.jLabel_sname.setText(this.jTextField_uname.getText());
                                        keeper.setVisible(true);
                                        this.setVisible(false);

                                    }

                                }
                            }
                        }
                    }
                }
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jButton_signinActionPerformed
    
    private void jTextField_unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_unameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cancel;
    private javax.swing.JButton jButton_signin;
    private javax.swing.JComboBox<String> jComboBox_position;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_pass;
    private javax.swing.JLabel jLabel_pass1;
    private javax.swing.JLabel jLabel_uname;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_pass;
    public static javax.swing.JTextField jTextField_uname;
    // End of variables declaration//GEN-END:variables
}
