/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asian_paints;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Lavanjan
 */
public class Manage_staff extends javax.swing.JFrame {

    /**
     * Creates new form Manage_staff
     */
    public Manage_staff() {
        initComponents();
        Show_details_staff();
        setExtendedState(getExtendedState()|JFrame.MAXIMIZED_BOTH);
    }
    
    
    public Connection getConnection()
    {
        Connection con;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/Asian_Paints", "root", "");
            return con;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
    
    
    public ArrayList<Display_staff_and_edit> getStafflist()
    {
        ArrayList<Display_staff_and_edit> stafflist = new ArrayList<Display_staff_and_edit>();
        Connection connection = getConnection();
        String query = "SELECT * FROM `login`";
        Statement st;
        ResultSet rs;
        
        try {
            st = connection.createStatement();
            rs = st.executeQuery(query);
            Display_staff_and_edit staff;
            
            while(rs.next())
            {
                staff = new Display_staff_and_edit(rs.getInt("empid"),rs.getString("firstname"),rs.getString("lastname"),rs.getString("username"),rs.getString("password"),rs.getString("address"),rs.getString("number"),rs.getString("gender"),rs.getString("roll"));
                stafflist.add(staff);
            }
        } catch (Exception e) {
        }
        return stafflist;
    }
    
 // DISPLAY TABLE
    
     public void Show_details_staff()
    {
     ArrayList<Display_staff_and_edit> list = getStafflist();
     DefaultTableModel model = (DefaultTableModel)jTable_display_users.getModel();
     Object[] row = new Object[9];
     for(int i = 0; i<list.size();i++)
     {
         row[0] = list.get(i).getID();
         row[1] = list.get(i).getfname();
         row[2] = list.get(i).getlname();
         row[3] = list.get(i).getuname();
         row[4] = list.get(i).getpass();
         row[5] = list.get(i).getAddr();
         row[6] = list.get(i).getnum();
         row[7] = list.get(i).getgen();
         row[8] = list.get(i).getroll();
         
         model.addRow(row);
         
         
     }
    }
     
     public void excuteSQlQuery(String query, String message)
     {
         Connection con = getConnection();
         Statement st;
         try {
             st = con.createStatement();
             if((st.executeUpdate(query)) == 1)
             {
                 // Refresh Data
                 DefaultTableModel model = (DefaultTableModel)jTable_display_users.getModel();
                 model.setRowCount(0);
                 Show_details_staff();
                 
                 JOptionPane.showMessageDialog(null, "Dta "+message+" Successfully");
             }else{
                 JOptionPane.showMessageDialog(null, "Dta Not"+message);
             }
         } catch (Exception ex) {
             ex.printStackTrace();
         }
     }
    
   
    
    
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_empid_staff = new javax.swing.JTextField();
        jTextField_fname_staff = new javax.swing.JTextField();
        jTextField_lname_staff = new javax.swing.JTextField();
        jTextField_uname_staff = new javax.swing.JTextField();
        jTextField_pass_staff = new javax.swing.JTextField();
        jTextField_addr_staff = new javax.swing.JTextField();
        jTextField_num_staff = new javax.swing.JTextField();
        jButton_dele_staff = new javax.swing.JButton();
        jButton_upd_staff = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_display_users = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton_male = new javax.swing.JRadioButton();
        jRadioButton_female = new javax.swing.JRadioButton();
        jRadioButton_cash = new javax.swing.JRadioButton();
        jRadioButton_Stock = new javax.swing.JRadioButton();
        jRadioButton_manager = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton_exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Nueva Std", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Emp ID:");

        jLabel2.setFont(new java.awt.Font("Nueva Std", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Firstname:");

        jLabel3.setFont(new java.awt.Font("Nueva Std", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText(" Lastname:");

        jLabel4.setFont(new java.awt.Font("Nueva Std", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Username:");

        jLabel5.setFont(new java.awt.Font("Nueva Std", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Password:");

        jLabel6.setFont(new java.awt.Font("Nueva Std", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Address:");

        jLabel7.setFont(new java.awt.Font("Nueva Std", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Number:");

        jTextField_empid_staff.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_empid_staff.setFont(new java.awt.Font("Nueva Std", 1, 14)); // NOI18N
        jTextField_empid_staff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextField_fname_staff.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_fname_staff.setFont(new java.awt.Font("Nueva Std", 1, 14)); // NOI18N
        jTextField_fname_staff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextField_lname_staff.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_lname_staff.setFont(new java.awt.Font("Nueva Std", 1, 14)); // NOI18N
        jTextField_lname_staff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextField_uname_staff.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_uname_staff.setFont(new java.awt.Font("Nueva Std", 1, 14)); // NOI18N
        jTextField_uname_staff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextField_pass_staff.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_pass_staff.setFont(new java.awt.Font("Nueva Std", 1, 14)); // NOI18N
        jTextField_pass_staff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField_pass_staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_pass_staffActionPerformed(evt);
            }
        });

        jTextField_addr_staff.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_addr_staff.setFont(new java.awt.Font("Nueva Std", 1, 14)); // NOI18N
        jTextField_addr_staff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField_addr_staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_addr_staffActionPerformed(evt);
            }
        });

        jTextField_num_staff.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_num_staff.setFont(new java.awt.Font("Nueva Std", 1, 14)); // NOI18N
        jTextField_num_staff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField_num_staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_num_staffActionPerformed(evt);
            }
        });
        jTextField_num_staff.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_num_staffKeyTyped(evt);
            }
        });

        jButton_dele_staff.setBackground(new java.awt.Color(0, 102, 102));
        jButton_dele_staff.setFont(new java.awt.Font("Nueva Std", 1, 15)); // NOI18N
        jButton_dele_staff.setForeground(new java.awt.Color(0, 0, 0));
        jButton_dele_staff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asian_paints/Image/Button-Delete-icon.png"))); // NOI18N
        jButton_dele_staff.setText("Delete");
        jButton_dele_staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_dele_staffActionPerformed(evt);
            }
        });

        jButton_upd_staff.setBackground(new java.awt.Color(0, 102, 102));
        jButton_upd_staff.setFont(new java.awt.Font("Nueva Std", 1, 15)); // NOI18N
        jButton_upd_staff.setForeground(new java.awt.Color(0, 0, 0));
        jButton_upd_staff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asian_paints/Image/Edit-validated-icon.png"))); // NOI18N
        jButton_upd_staff.setText("Update");
        jButton_upd_staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_upd_staffActionPerformed(evt);
            }
        });

        jTable_display_users.setFont(new java.awt.Font("Nueva Std", 1, 14)); // NOI18N
        jTable_display_users.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EmpID", "Firstname", "Lastname", "Username", "Password", "Address", "Number", "Gender", "Roll"
            }
        ));
        jTable_display_users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_display_usersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_display_users);

        jLabel8.setFont(new java.awt.Font("Nueva Std", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Gender:");

        jLabel9.setFont(new java.awt.Font("Nueva Std", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Roll:");

        jRadioButton_male.setBackground(new java.awt.Color(0, 102, 102));
        jRadioButton_male.setFont(new java.awt.Font("Nueva Std", 1, 14)); // NOI18N
        jRadioButton_male.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton_male.setText("MALE");
        jRadioButton_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_maleActionPerformed(evt);
            }
        });

        jRadioButton_female.setBackground(new java.awt.Color(0, 102, 102));
        jRadioButton_female.setFont(new java.awt.Font("Nueva Std", 1, 14)); // NOI18N
        jRadioButton_female.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton_female.setText("FEMALE");
        jRadioButton_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_femaleActionPerformed(evt);
            }
        });

        jRadioButton_cash.setBackground(new java.awt.Color(0, 102, 102));
        jRadioButton_cash.setFont(new java.awt.Font("Nueva Std", 1, 14)); // NOI18N
        jRadioButton_cash.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton_cash.setText("Cashier");
        jRadioButton_cash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_cashActionPerformed(evt);
            }
        });

        jRadioButton_Stock.setBackground(new java.awt.Color(0, 102, 102));
        jRadioButton_Stock.setFont(new java.awt.Font("Nueva Std", 1, 14)); // NOI18N
        jRadioButton_Stock.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton_Stock.setText("Stock keeper");
        jRadioButton_Stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_StockActionPerformed(evt);
            }
        });

        jRadioButton_manager.setBackground(new java.awt.Color(0, 102, 102));
        jRadioButton_manager.setFont(new java.awt.Font("Nueva Std", 1, 14)); // NOI18N
        jRadioButton_manager.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton_manager.setText("Manager");
        jRadioButton_manager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_managerActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asian_paints/Image/Black.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Nueva Std", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Manage Staff Details");
        jLabel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Nueva Std", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asian_paints/Image/Arrow-Back-icon.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton_exit.setBackground(new java.awt.Color(0, 102, 102));
        jButton_exit.setFont(new java.awt.Font("Nueva Std", 1, 18)); // NOI18N
        jButton_exit.setForeground(new java.awt.Color(0, 0, 0));
        jButton_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asian_paints/Image/Button-Red-Cancel-icon (1).png"))); // NOI18N
        jButton_exit.setText("Exit");
        jButton_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField_uname_staff)
                                            .addComponent(jTextField_pass_staff, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel1)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField_lname_staff)
                                            .addComponent(jTextField_fname_staff)
                                            .addComponent(jTextField_empid_staff, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField_num_staff, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                                            .addComponent(jTextField_addr_staff))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton_dele_staff, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton_upd_staff, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jRadioButton_male, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(26, 26, 26)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(108, 108, 108)
                                                        .addComponent(jRadioButton_Stock))
                                                    .addComponent(jRadioButton_female, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jRadioButton_cash, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton_manager, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(11, 11, 11))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_exit))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 827, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_empid_staff, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_fname_staff, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_lname_staff, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_uname_staff, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_pass_staff, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_addr_staff, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_num_staff, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton_male, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton_female, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton_manager, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton_cash, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_dele_staff, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_upd_staff, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_num_staffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_num_staffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_num_staffActionPerformed

    private void jTable_display_usersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_display_usersMouseClicked
        // TODO add your handling code here:
        
        int i = jTable_display_users.getSelectedRow();
        TableModel model = jTable_display_users.getModel();
        jTextField_empid_staff.setText(model.getValueAt(i,0).toString());
        jTextField_fname_staff.setText(model.getValueAt(i,1).toString());
        jTextField_lname_staff.setText(model.getValueAt(i,2).toString());
        jTextField_uname_staff.setText(model.getValueAt(i,3).toString());
        jTextField_pass_staff.setText(model.getValueAt(i,4).toString());
        jTextField_addr_staff.setText(model.getValueAt(i,5).toString());
        jTextField_num_staff.setText(model.getValueAt(i,6).toString());
        String gender = model.getValueAt(i, 7).toString();
        if(gender.equals("MALE"))
        {
            jRadioButton_male.setSelected(true);
            jRadioButton_female.setSelected(false);
        }
        else{
            jRadioButton_female.setSelected(true);
            jRadioButton_male.setSelected(false);
        }
        
     /*  String roll = model.getValueAt(i, 8).toString();
        if(roll.equals("CASHIER"))
        {
            jRadioButton_cash.setSelected(true);
            jRadioButton_Stock.setSelected(false);
        }
        else{
            jRadioButton_Stock.setSelected(true);
            jRadioButton_cash.setSelected(false);
        }*/
        
        
        
        
        String roll = model.getValueAt(i, 8).toString();
        switch(roll){
            case "SELECT":
                jRadioButton_cash.setSelected(false);
            jRadioButton_Stock.setSelected(false);
            jRadioButton_manager.setSelected(false);
            break;
            
            case "CASHIER":
                jRadioButton_cash.setSelected(true);
            jRadioButton_Stock.setSelected(false);
            jRadioButton_manager.setSelected(false);
            break;
            
            case "STOCK KEEPER":
                jRadioButton_cash.setSelected(false);
            jRadioButton_Stock.setSelected(true);
            jRadioButton_manager.setSelected(false);
            
            break;
            
            
            case "MANAGER":
                jRadioButton_cash.setSelected(false);
            jRadioButton_Stock.setSelected(false);
            jRadioButton_manager.setSelected(true);
            break;
            
            
            default :
                jRadioButton_cash.setSelected(false);
            jRadioButton_Stock.setSelected(false);
            jRadioButton_manager.setSelected(false);
                
        }
        
        
        
        
        
        
        
        
        
        
        
        
        
     //   jComboBox_gender_staff.getSelectedItem()(model.getValueAt(i,0).toString());
       // jComboBox_roll_staff.setText(model.getValueAt(i,0).toString());
        
        
        
    }//GEN-LAST:event_jTable_display_usersMouseClicked

    private void jTextField_pass_staffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_pass_staffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_pass_staffActionPerformed

    private void jTextField_addr_staffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_addr_staffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_addr_staffActionPerformed

    private void jRadioButton_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_femaleActionPerformed
        // TODO add your handling code here:
        jRadioButton_female.setEnabled(false);
        
    }//GEN-LAST:event_jRadioButton_femaleActionPerformed

    private void jRadioButton_StockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_StockActionPerformed
        // TODO add your handling code here:
        jRadioButton_Stock.setEnabled(false);
        
    }//GEN-LAST:event_jRadioButton_StockActionPerformed

    private void jRadioButton_managerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_managerActionPerformed
        // TODO add your handling code here:
        jRadioButton_manager.setEnabled(false);
        
        
    }//GEN-LAST:event_jRadioButton_managerActionPerformed

    private void jRadioButton_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_maleActionPerformed
        // TODO add your handling code here:
        
        jRadioButton_male.setEnabled(false);
    }//GEN-LAST:event_jRadioButton_maleActionPerformed

    private void jRadioButton_cashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_cashActionPerformed
        // TODO add your handling code here:
        jRadioButton_cash.setEnabled(false);
        
        
    }//GEN-LAST:event_jRadioButton_cashActionPerformed

    private void jButton_upd_staffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_upd_staffActionPerformed
        // TODO add your handling code here:
        // UPDATE
        
        
        String quary = "UPDATE `login` SET `firstname`='"+jTextField_fname_staff.getText()+"',`lastname`='"+jTextField_lname_staff.getText()+"',`username`='"+jTextField_uname_staff.getText()+"',`password`='"+jTextField_pass_staff.getText()+"',`address`='"+jTextField_addr_staff.getText()+"',`number`='"+jTextField_num_staff.getText()+"' WHERE `empid`="+jTextField_empid_staff.getText();
        excuteSQlQuery(quary, "Updated");
    }//GEN-LAST:event_jButton_upd_staffActionPerformed

    private void jButton_dele_staffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_dele_staffActionPerformed
        // TODO add your handling code here:
        
        //DELETED
        
        String quary = "DELETE FROM `login` WHERE `empid`="+jTextField_empid_staff.getText();
        excuteSQlQuery(quary, "Deleted");
    }//GEN-LAST:event_jButton_dele_staffActionPerformed

    private void jTextField_num_staffKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_num_staffKeyTyped
        // TODO add your handling code here:
        
         if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
         }
    }//GEN-LAST:event_jTextField_num_staffKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // BACK TO MANAGER PAGE
        Manager manager = new Manager();
        manager.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_exitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_staff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_dele_staff;
    private javax.swing.JButton jButton_exit;
    private javax.swing.JButton jButton_upd_staff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton_Stock;
    private javax.swing.JRadioButton jRadioButton_cash;
    private javax.swing.JRadioButton jRadioButton_female;
    private javax.swing.JRadioButton jRadioButton_male;
    private javax.swing.JRadioButton jRadioButton_manager;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_display_users;
    private javax.swing.JTextField jTextField_addr_staff;
    private javax.swing.JTextField jTextField_empid_staff;
    private javax.swing.JTextField jTextField_fname_staff;
    private javax.swing.JTextField jTextField_lname_staff;
    private javax.swing.JTextField jTextField_num_staff;
    private javax.swing.JTextField jTextField_pass_staff;
    private javax.swing.JTextField jTextField_uname_staff;
    // End of variables declaration//GEN-END:variables
}
