/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asian_paints;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Lavanjan
 */
public class Manage_customer extends javax.swing.JFrame {

    /**
     * Creates new form Manage_customer
     */
    public Manage_customer() {
        initComponents();
        Show_details_customer();
        setExtendedState(getExtendedState()|JFrame.MAXIMIZED_BOTH);
    }
    
     public Connection getConnection()
    {
        Connection con;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/Asian_Paints", "root", "");
            return con;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
     
     
     
     
     public ArrayList<Customer> getCuslist()
    {
        ArrayList<Customer> cuslist = new ArrayList<Customer>();
        Connection connection = getConnection();
        String query = "SELECT * FROM `customer`";
        Statement st;
        ResultSet rs;
        
        try {
            st = connection.createStatement();
            rs = st.executeQuery(query);
            Customer cus;
            
            while(rs.next())
            {
                cus = new Customer(rs.getInt("cusid"),rs.getString("firstname"),rs.getString("lastname"),rs.getString("address"),rs.getString("number"));
                cuslist.add(cus);
            }
        } catch (Exception e) {
        }
        return cuslist;
    }
     
     
     
    // VIEW CUSTOMER TABLE
     
     public void Show_details_customer()
    {
     ArrayList<Customer> list = getCuslist();
     DefaultTableModel model = (DefaultTableModel)jTable_display_customers.getModel();
     Object[] row = new Object[9];
     for(int i = 0; i<list.size();i++)
     {
         row[0] = list.get(i).getID();
         row[1] = list.get(i).getfname();
         row[2] = list.get(i).getlname();
         row[3] = list.get(i).getAddr();
         row[4] = list.get(i).getnum();
         
         
         model.addRow(row);
         
         
     }
    }
    
     
     
     public void excuteSQlQuery(String query, String message)
     {
         Connection con = getConnection();
         Statement st;
         try {
             st = con.createStatement();
             if((st.executeUpdate(query)) == 1)
             {
                 // Refresh Data
                 DefaultTableModel model = (DefaultTableModel)jTable_display_customers.getModel();
                 model.setRowCount(0);
                 Show_details_customer();
                 
                 JOptionPane.showMessageDialog(null, "Data "+message+" Successfully");
             }else{
                 JOptionPane.showMessageDialog(null, "Data Not"+message);
             }
         } catch (Exception ex) {
             ex.printStackTrace();
         }
     }
     
     
     
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField_num_customer = new javax.swing.JTextField();
        jButton_dele_cus = new javax.swing.JButton();
        jButton_upd_cus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_display_customers = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField_cusid_customer = new javax.swing.JTextField();
        jTextField_fname_customer = new javax.swing.JTextField();
        jTextField_lname_customer = new javax.swing.JTextField();
        jTextField_addr_customer = new javax.swing.JTextField();
        jButton_dele_cus1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jTextField_num_customer.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_num_customer.setFont(new java.awt.Font("Nueva Std", 1, 14)); // NOI18N
        jTextField_num_customer.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_num_customer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField_num_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_num_customerActionPerformed(evt);
            }
        });
        jTextField_num_customer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_num_customerKeyTyped(evt);
            }
        });

        jButton_dele_cus.setBackground(new java.awt.Color(0, 102, 102));
        jButton_dele_cus.setFont(new java.awt.Font("Nueva Std", 1, 16)); // NOI18N
        jButton_dele_cus.setForeground(new java.awt.Color(0, 0, 0));
        jButton_dele_cus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asian_paints/Image/Button-Delete-icon.png"))); // NOI18N
        jButton_dele_cus.setText("Delete");
        jButton_dele_cus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_dele_cusActionPerformed(evt);
            }
        });

        jButton_upd_cus.setBackground(new java.awt.Color(0, 102, 102));
        jButton_upd_cus.setFont(new java.awt.Font("Nueva Std", 1, 16)); // NOI18N
        jButton_upd_cus.setForeground(new java.awt.Color(0, 0, 0));
        jButton_upd_cus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asian_paints/Image/Edit-validated-icon.png"))); // NOI18N
        jButton_upd_cus.setText("Update");
        jButton_upd_cus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_upd_cusActionPerformed(evt);
            }
        });

        jTable_display_customers.setBackground(new java.awt.Color(0, 102, 102));
        jTable_display_customers.setFont(new java.awt.Font("Nueva Std", 1, 14)); // NOI18N
        jTable_display_customers.setForeground(new java.awt.Color(0, 0, 0));
        jTable_display_customers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CustomerID", "Firstname", "Lastname", "Address", "Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_display_customers.setGridColor(new java.awt.Color(51, 51, 255));
        jTable_display_customers.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jTable_display_customers.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTable_display_customers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_display_customersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_display_customers);

        jLabel1.setFont(new java.awt.Font("Nueva Std", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Cus ID:");

        jLabel2.setFont(new java.awt.Font("Nueva Std", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Firstname:");

        jLabel3.setFont(new java.awt.Font("Nueva Std", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText(" Lastname:");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asian_paints/Image/Black.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Nueva Std", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Address:");

        jLabel7.setFont(new java.awt.Font("Nueva Std", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Number:");

        jLabel11.setFont(new java.awt.Font("Nueva Std", 1, 40)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Manage Customer Details");
        jLabel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Nueva Std", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asian_paints/Image/Arrow-Back-icon.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField_cusid_customer.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_cusid_customer.setFont(new java.awt.Font("Nueva Std", 1, 14)); // NOI18N
        jTextField_cusid_customer.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_cusid_customer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField_cusid_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_cusid_customerActionPerformed(evt);
            }
        });

        jTextField_fname_customer.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_fname_customer.setFont(new java.awt.Font("Nueva Std", 1, 14)); // NOI18N
        jTextField_fname_customer.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_fname_customer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextField_lname_customer.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_lname_customer.setFont(new java.awt.Font("Nueva Std", 1, 14)); // NOI18N
        jTextField_lname_customer.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_lname_customer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField_lname_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_lname_customerActionPerformed(evt);
            }
        });

        jTextField_addr_customer.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_addr_customer.setFont(new java.awt.Font("Nueva Std", 1, 14)); // NOI18N
        jTextField_addr_customer.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_addr_customer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField_addr_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_addr_customerActionPerformed(evt);
            }
        });

        jButton_dele_cus1.setBackground(new java.awt.Color(0, 102, 102));
        jButton_dele_cus1.setFont(new java.awt.Font("Nueva Std", 1, 16)); // NOI18N
        jButton_dele_cus1.setForeground(new java.awt.Color(0, 0, 0));
        jButton_dele_cus1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asian_paints/Image/add-contact-icon.png"))); // NOI18N
        jButton_dele_cus1.setText("Add");
        jButton_dele_cus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_dele_cus1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Nueva Std", 1, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asian_paints/Image/Actions-edit-clear-history-icon.png"))); // NOI18N
        jButton2.setText("Sales");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setFont(new java.awt.Font("Nueva Std", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asian_paints/Image/Button-Red-Cancel-icon (1).png"))); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_cusid_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_fname_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_lname_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_addr_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_num_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton_dele_cus1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton_dele_cus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton_upd_cus, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jLabel11)))
                        .addGap(40, 57, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_cusid_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_fname_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_lname_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_addr_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_num_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_dele_cus1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_upd_cus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                            .addComponent(jButton_dele_cus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addContainerGap(194, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_addr_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_addr_customerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_addr_customerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // BACK TO MANAGER PAGE
        Manager manager = new Manager();
        manager.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable_display_customersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_display_customersMouseClicked
        // TODO add your handling code here:

        int i = jTable_display_customers.getSelectedRow();
        TableModel model = jTable_display_customers.getModel();
        jTextField_cusid_customer.setText(model.getValueAt(i,0).toString());
        jTextField_fname_customer.setText(model.getValueAt(i,1).toString());
        jTextField_lname_customer.setText(model.getValueAt(i,2).toString());
        jTextField_addr_customer.setText(model.getValueAt(i,3).toString());
        jTextField_num_customer.setText(model.getValueAt(i,4).toString());
        

        /*  String roll = model.getValueAt(i, 8).toString();
        if(roll.equals("CASHIER"))
        {
            jRadioButton_cash.setSelected(true);
            jRadioButton_Stock.setSelected(false);
        }
        else{
            jRadioButton_Stock.setSelected(true);
            jRadioButton_cash.setSelected(false);
        }*/

        

        

        //   jComboBox_gender_staff.getSelectedItem()(model.getValueAt(i,0).toString());
        // jComboBox_roll_staff.setText(model.getValueAt(i,0).toString());
    }//GEN-LAST:event_jTable_display_customersMouseClicked

    private void jButton_upd_cusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_upd_cusActionPerformed
        // TODO add your handling code here:
        // UPDATE

        String quary = "UPDATE `customer` SET `firstname`='"+jTextField_fname_customer.getText()+"',`lastname`='"+jTextField_lname_customer.getText()+"',`address`='"+jTextField_addr_customer.getText()+"',`number`='"+jTextField_num_customer.getText()+"' WHERE `cusid`="+jTextField_cusid_customer.getText();
        excuteSQlQuery(quary, "Updated");
    }//GEN-LAST:event_jButton_upd_cusActionPerformed

    private void jButton_dele_cusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_dele_cusActionPerformed
        // TODO add your handling code here:

        //DELETED

        String quary = "DELETE FROM `customer` WHERE `empid`="+jTextField_cusid_customer.getText();
        excuteSQlQuery(quary, "Deleted");
    }//GEN-LAST:event_jButton_dele_cusActionPerformed

    private void jTextField_num_customerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_num_customerKeyTyped
        // TODO add your handling code here:

        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_num_customerKeyTyped

    private void jTextField_num_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_num_customerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_num_customerActionPerformed

    private void jButton_dele_cus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_dele_cus1ActionPerformed
        // TODO add your handling code here:
        //REGISTER
        
        String quary = "INSERT INTO `customer`(`firstname`, `lastname`, `address`, `number`) VALUES ('"+jTextField_fname_customer.getText()+"','"+jTextField_lname_customer.getText()+"','"+jTextField_addr_customer.getText()+"','"+jTextField_num_customer.getText()+"')";
        excuteSQlQuery(quary, "Added");
        
        jTextField_fname_customer.setText("");
        jTextField_lname_customer.setText("");
        jTextField_addr_customer.setText("");
        jTextField_num_customer.setText("");
        
        
        
    }//GEN-LAST:event_jButton_dele_cus1ActionPerformed

    private void jTextField_cusid_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_cusid_customerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_cusid_customerActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       
        Make_sales sales = new Make_sales();
        Make_sales.jTextField_cusid_sales.setText(this.jTextField_cusid_customer.getText());
        sales.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField_lname_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_lname_customerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_lname_customerActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here
        
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton_dele_cus;
    private javax.swing.JButton jButton_dele_cus1;
    private javax.swing.JButton jButton_upd_cus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_display_customers;
    private javax.swing.JTextField jTextField_addr_customer;
    public static javax.swing.JTextField jTextField_cusid_customer;
    private javax.swing.JTextField jTextField_fname_customer;
    private javax.swing.JTextField jTextField_lname_customer;
    private javax.swing.JTextField jTextField_num_customer;
    // End of variables declaration//GEN-END:variables
}
