/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asian_paints;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Lavanjan
 */
public class Paint_stockkeeper extends javax.swing.JFrame {

    /**
     * Creates new form Paint_stockkeeper
     */
    public Paint_stockkeeper() {
        initComponents();
        Show_details_paint();
        setExtendedState(getExtendedState()|JFrame.MAXIMIZED_BOTH);
    }
    
    
    
     public Connection getConnection()
    {
        Connection con;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/Asian_Paints", "root", "");
            return con;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
    
    
    
    public ArrayList<Paint> getPaintlist()
    {
        ArrayList<Paint> paintlist = new ArrayList<Paint>();
        Connection connection = getConnection();
        String query = "SELECT * FROM `paint_stock`";
        Statement st;
        ResultSet rs;
        
        try {
            st = connection.createStatement();
            rs = st.executeQuery(query);
            Paint ap;
            
            while(rs.next())
            {
                ap = new Paint(rs.getInt("proid"),rs.getString("modelname"),rs.getString("color"),rs.getInt("price"),rs.getInt("qantity"));
                paintlist.add(ap);
            }
        } catch (Exception e) {
        }
        return paintlist;
    }
    
    
    //VIEW PAINT TABLE
    
     public void Show_details_paint()
    {
     ArrayList<Paint> list = getPaintlist();
     DefaultTableModel model = (DefaultTableModel)jTable_display_paint.getModel();
     Object[] row = new Object[9];
     for(int i = 0; i<list.size();i++)
     {
         row[0] = list.get(i).getID();
         row[1] = list.get(i).getmodelname();
         row[2] = list.get(i).getcolor();
         row[3] = list.get(i).getprice();
         row[4] = list.get(i).getqty();
         
         
         model.addRow(row);
         
         
     }
    }
     
     
     
     public void excuteSQlQuery(String query, String message)
     {
         Connection con = getConnection();
         Statement st;
         try {
             st = con.createStatement();
             if((st.executeUpdate(query)) == 1)
             {
                 // Refresh Data
                 DefaultTableModel model = (DefaultTableModel)jTable_display_paint.getModel();
                 model.setRowCount(0);
                 Show_details_paint();
                 
                 JOptionPane.showMessageDialog(null, "Data "+message+" Successfully");
             }else{
                 JOptionPane.showMessageDialog(null, "Data Not"+message);
             }
         } catch (Exception ex) {
             ex.printStackTrace();
         }
     }
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTextField_qty_paint = new javax.swing.JTextField();
        jButton_dele_paint = new javax.swing.JButton();
        jButton_upd_paint = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_display_paint = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField_proid_paint = new javax.swing.JTextField();
        jTextField_model_paint = new javax.swing.JTextField();
        jTextField_color_paint = new javax.swing.JTextField();
        jTextField_price_paint = new javax.swing.JTextField();
        jButton_add_paint = new javax.swing.JButton();
        jTextField_search = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jTextField_qty_paint.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_qty_paint.setFont(new java.awt.Font("Nueva Std", 1, 14)); // NOI18N
        jTextField_qty_paint.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_qty_paint.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField_qty_paint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_qty_paintActionPerformed(evt);
            }
        });
        jTextField_qty_paint.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_qty_paintKeyTyped(evt);
            }
        });

        jButton_dele_paint.setBackground(new java.awt.Color(0, 102, 102));
        jButton_dele_paint.setFont(new java.awt.Font("Nueva Std", 1, 15)); // NOI18N
        jButton_dele_paint.setForeground(new java.awt.Color(0, 0, 0));
        jButton_dele_paint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asian_paints/Image/Button-Delete-icon.png"))); // NOI18N
        jButton_dele_paint.setText("Delete");
        jButton_dele_paint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_dele_paintActionPerformed(evt);
            }
        });

        jButton_upd_paint.setBackground(new java.awt.Color(0, 102, 102));
        jButton_upd_paint.setFont(new java.awt.Font("Nueva Std", 1, 15)); // NOI18N
        jButton_upd_paint.setForeground(new java.awt.Color(0, 0, 0));
        jButton_upd_paint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asian_paints/Image/Edit-validated-icon.png"))); // NOI18N
        jButton_upd_paint.setText("Update");
        jButton_upd_paint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_upd_paintActionPerformed(evt);
            }
        });

        jTable_display_paint.setBackground(new java.awt.Color(0, 102, 102));
        jTable_display_paint.setFont(new java.awt.Font("Nueva Std", 1, 14)); // NOI18N
        jTable_display_paint.setForeground(new java.awt.Color(0, 0, 0));
        jTable_display_paint.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Model Name", "Paint Color", "Unit Price", "Quantity"
            }
        ));
        jTable_display_paint.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jTable_display_paint.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTable_display_paint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_display_paintMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_display_paint);

        jLabel1.setFont(new java.awt.Font("Nueva Std", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Pro ID:");

        jLabel2.setFont(new java.awt.Font("Nueva Std", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Model Name:");

        jLabel3.setFont(new java.awt.Font("Nueva Std", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText(" Paint Color:");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asian_paints/Image/Black.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Nueva Std", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Unit Price:");

        jLabel7.setFont(new java.awt.Font("Nueva Std", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Quantity:");

        jLabel11.setFont(new java.awt.Font("Nueva Std", 1, 40)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("    Manage Paint Details");
        jLabel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Nueva Std", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asian_paints/Image/Arrow-Back-icon.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField_proid_paint.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_proid_paint.setFont(new java.awt.Font("Nueva Std", 1, 14)); // NOI18N
        jTextField_proid_paint.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_proid_paint.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField_proid_paint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_proid_paintActionPerformed(evt);
            }
        });

        jTextField_model_paint.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_model_paint.setFont(new java.awt.Font("Nueva Std", 1, 14)); // NOI18N
        jTextField_model_paint.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_model_paint.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextField_color_paint.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_color_paint.setFont(new java.awt.Font("Nueva Std", 1, 14)); // NOI18N
        jTextField_color_paint.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_color_paint.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField_color_paint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_color_paintActionPerformed(evt);
            }
        });

        jTextField_price_paint.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_price_paint.setFont(new java.awt.Font("Nueva Std", 1, 14)); // NOI18N
        jTextField_price_paint.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_price_paint.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField_price_paint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_price_paintActionPerformed(evt);
            }
        });

        jButton_add_paint.setBackground(new java.awt.Color(0, 102, 102));
        jButton_add_paint.setFont(new java.awt.Font("Nueva Std", 1, 15)); // NOI18N
        jButton_add_paint.setForeground(new java.awt.Color(0, 0, 0));
        jButton_add_paint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asian_paints/Image/add-contact-icon.png"))); // NOI18N
        jButton_add_paint.setText("Add");
        jButton_add_paint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_add_paintActionPerformed(evt);
            }
        });

        jTextField_search.setBackground(new java.awt.Color(51, 51, 51));
        jTextField_search.setFont(new java.awt.Font("Nueva Std", 1, 14)); // NOI18N
        jTextField_search.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_searchActionPerformed(evt);
            }
        });
        jTextField_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_searchKeyReleased(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Nueva Std", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asian_paints/Image/Button-Red-Cancel-icon (1).png"))); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextField_proid_paint, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_price_paint, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_color_paint, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_model_paint, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_qty_paint, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButton_add_paint, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton_upd_paint, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jTextField_search, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(111, 111, 111))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jButton_dele_paint, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(216, 216, 216)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(243, 243, 243)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(112, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField_search, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_proid_paint, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_model_paint, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_color_paint, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_price_paint, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_qty_paint, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_upd_paint, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_add_paint, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jButton_dele_paint, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(199, 199, 199))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_qty_paintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_qty_paintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_qty_paintActionPerformed

    private void jTextField_qty_paintKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_qty_paintKeyTyped
        // TODO add your handling code here:

        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_qty_paintKeyTyped

    private void jButton_dele_paintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_dele_paintActionPerformed
        // TODO add your handling code here:

        //DELETED

        String quary = "DELETE FROM `paint_stock` WHERE `proid`="+jTextField_proid_paint.getText();
        excuteSQlQuery(quary, "Deleted");

        //FOR EMPTY FIELD
        jTextField_proid_paint.setText("");
        jTextField_model_paint.setText("");
        jTextField_color_paint.setText("");
        jTextField_price_paint.setText("");
        jTextField_qty_paint.setText("");

    }//GEN-LAST:event_jButton_dele_paintActionPerformed

    private void jButton_upd_paintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_upd_paintActionPerformed
        // TODO add your handling code here:
        // UPDATE

        String quary = "UPDATE `paint_stock` SET `modelname`='"+jTextField_model_paint.getText()+"',`color`='"+jTextField_color_paint.getText()+"',`price`='"+jTextField_price_paint.getText()+"',`qantity`='"+jTextField_qty_paint.getText()+"' WHERE `proid`="+jTextField_proid_paint.getText();
        excuteSQlQuery(quary, "Updated");

        // FOR EMPTY FIELD
        jTextField_proid_paint.setText("");
        jTextField_model_paint.setText("");
        jTextField_color_paint.setText("");
        jTextField_price_paint.setText("");
        jTextField_qty_paint.setText("");

    }//GEN-LAST:event_jButton_upd_paintActionPerformed

    private void jTable_display_paintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_display_paintMouseClicked
        // TODO add your handling code here:

        int i = jTable_display_paint.getSelectedRow();
        TableModel model = jTable_display_paint.getModel();
        jTextField_proid_paint.setText(model.getValueAt(i,0).toString());
        jTextField_model_paint.setText(model.getValueAt(i,1).toString());
        jTextField_color_paint.setText(model.getValueAt(i,2).toString());
        jTextField_price_paint.setText(model.getValueAt(i,3).toString());
        jTextField_qty_paint.setText(model.getValueAt(i,4).toString());

        /*  String roll = model.getValueAt(i, 8).toString();
        if(roll.equals("CASHIER"))
        {
            jRadioButton_cash.setSelected(true);
            jRadioButton_Stock.setSelected(false);
        }
        else{
            jRadioButton_Stock.setSelected(true);
            jRadioButton_cash.setSelected(false);
        }*/

        //   jComboBox_gender_staff.getSelectedItem()(model.getValueAt(i,0).toString());
        // jComboBox_roll_staff.setText(model.getValueAt(i,0).toString());
    }//GEN-LAST:event_jTable_display_paintMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // BACK TO MANAGER PAGE
        Stock_Keeper stock = new Stock_Keeper();
        stock.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField_proid_paintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_proid_paintActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField_proid_paintActionPerformed

    private void jTextField_color_paintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_color_paintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_color_paintActionPerformed

    private void jTextField_price_paintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_price_paintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_price_paintActionPerformed

    private void jButton_add_paintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_add_paintActionPerformed
        // TODO add your handling code here:
        //REGISTER

        String quary = "INSERT INTO `paint_stock`(`modelname`, `color`, `price`, `qantity`) VALUES ('"+jTextField_model_paint.getText()+"','"+jTextField_color_paint.getText()+"','"+jTextField_price_paint.getText()+"','"+jTextField_qty_paint.getText()+"')";
        excuteSQlQuery(quary, "Added");

        jTextField_model_paint.setText("");
        jTextField_color_paint.setText("");
        jTextField_price_paint.setText("");
        jTextField_qty_paint.setText("");
    }//GEN-LAST:event_jButton_add_paintActionPerformed

    private void jTextField_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_searchActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField_searchActionPerformed

    private void jTextField_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_searchKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField_searchKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paint_stockkeeper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paint_stockkeeper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paint_stockkeeper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paint_stockkeeper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paint_stockkeeper().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_add_paint;
    private javax.swing.JButton jButton_dele_paint;
    private javax.swing.JButton jButton_upd_paint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_display_paint;
    private javax.swing.JTextField jTextField_color_paint;
    private javax.swing.JTextField jTextField_model_paint;
    private javax.swing.JTextField jTextField_price_paint;
    private javax.swing.JTextField jTextField_proid_paint;
    private javax.swing.JTextField jTextField_qty_paint;
    public static javax.swing.JTextField jTextField_search;
    // End of variables declaration//GEN-END:variables
}
